In [1]:
%pip install scikit-learn==1.7.2

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python3 -m pip install --upgrade pip


In [2]:
from collections import defaultdict

import numpy as np
import json
import pickle

from sklearn.cluster import KMeans

In [3]:
# embeddings_input_path = '../data/Beauty/content_embeddings.pkl'
# semantic_index_output_path = '../data/Beauty/index_rqkmeans.json'

embeddings_input_path = '../data/Beauty/tuned_content_embeddings.pkl'
semantic_index_output_path = '../data/Beauty/tuned_index_rqkmeans.json'

In [4]:
import os
print(os.path.getsize(embeddings_input_path))

446333898


In [5]:
with open(embeddings_input_path, 'rb') as f:
    data = pickle.load(f)

item_ids = np.array(data['item_id'], dtype=np.int64)
X = np.array(data['embedding'], dtype=np.float32)

In [6]:
class RQKMeans:
    def __init__(
            self, 
            num_clusters, 
            num_codebooks, 
            init='k-means++', 
            max_iter=300, 
            tol=1e-4, 
            verbose=0, 
            random_state=42
    ):
        self.models = [
            KMeans(
                n_clusters=num_clusters,
                init=init,
                max_iter=max_iter,
                tol=tol,
                verbose=verbose,
                random_state=random_state + i,
            ) for i in range(num_codebooks)
        ]

    def fit(self, X, y=None):
        for model in self.models:
            y = model.fit_predict(X)
            X = X - model.cluster_centers_[y]
        return self

    def predict(self, X):
        result = []
        centroids = []
        for model in self.models:
            result.append(model.predict(X))
            centroids.append(model.cluster_centers_[result[-1]])
            X = X - centroids[-1]
        return np.stack(result, axis=-1)

In [7]:
rq_kmeans = RQKMeans(num_clusters=256, num_codebooks=3, max_iter=1000)

In [8]:
rq_kmeans.fit(X)

In [9]:
clusters = rq_kmeans.predict(X)

In [10]:
clusters[:10]

array([[104, 142, 163],
       [ 34,  15,  93],
       [ 79,  29, 253],
       [ 79,  29,  32],
       [ 79,  60,  14],
       [157, 107, 197],
       [ 90,  40, 122],
       [ 90, 212, 132],
       [250, 227, 209],
       [250, 181, 108]], dtype=int32)

In [11]:
clusters.shape

(12101, 3)

In [12]:
item_ids[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 9, 8])

In [13]:
item_ids.shape

(12101,)

In [14]:
X[:10]

array([[-0.05657047, -0.00550879,  0.04047301, ...,  0.00413161,
         0.00819374,  0.02012947],
       [-0.03789181, -0.00552349,  0.03701511, ..., -0.00067801,
        -0.00344397,  0.02287921],
       [-0.02963883,  0.00918462,  0.03302356, ..., -0.00963226,
        -0.00282938,  0.01196733],
       ...,
       [-0.03136437, -0.00049188,  0.02694709, ..., -0.00493038,
        -0.00354407,  0.01532388],
       [-0.0226947 , -0.00429587,  0.03406443, ...,  0.00400031,
        -0.00252151,  0.01756681],
       [-0.02070109,  0.00267115,  0.0326909 , ..., -0.00577452,
         0.00103506,  0.01281374]], dtype=float32)

In [15]:
X.shape

(12101, 4096)

In [16]:
# Create semantics mapping
inter = {}
sem_2_ids = defaultdict(list)
for idx, clusters in zip(item_ids, clusters):
    inter[int(idx)] = clusters.tolist()
    sem_2_ids[tuple(clusters.tolist())].append(int(idx))

# Solve collistions
for semantics, item_ids in sem_2_ids.items():
    assert len(item_ids) <= 256
    collision_solvers = np.random.permutation(256)[:len(item_ids)].tolist()
    for item_id, collision_solver in zip(item_ids, collision_solvers):
        # то есть получается shape стал 4, но не у всех, у кого-то все еще 3
        inter[item_id].append(collision_solver)
    
# Save semantics
with open(semantic_index_output_path, 'w') as f:
    json.dump(inter, f)

Посмотрим, насколько в пространстве близки эмбеды до и после tower (по идее это лучше положить в cf_finetune в раздел с прокси-метриками)

In [17]:
old_embeddings_input_path = '../data/Beauty/content_embeddings.pkl'

In [18]:
with open(old_embeddings_input_path, 'rb') as f:
    old_data = pickle.load(f)

old_item_ids = np.array(old_data['item_id'], dtype=np.int64)
old_X = np.array(old_data['embedding'], dtype=np.float32)

In [19]:
import torch.nn.functional as F
import torch

cos = F.cosine_similarity(F.normalize(torch.tensor(X)), F.normalize(torch.tensor(old_X)))
print('mean cos:', cos.mean().item(), 'std:', cos.std().item())

mean cos: -0.01302650012075901 std: 0.010602756403386593
